# Generated by Django 2.1.4 on 2018-12-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toplanti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rols',
        ),
        migrations.AddField(
            model_name='organizasyontutucu',
            name='textler',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='toplanti.Notlar'),
            preserve_default=False,
        ),
    ]
