# Generated by Django 2.1.4 on 2018-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplanti', '0002_auto_20181210_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizasyontutucu',
            name='textler',
        ),
        migrations.AddField(
            model_name='customer',
            name='text',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notlar',
        ),
    ]
